# -*- coding: utf-8 -*-
"""Kopia notatnika Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKjTNapEqj38tbQKHySR3J03RwDZ9Jho
"""

import numpy as np
import matplotlib.pyplot as plt

m = 1.0
q = 0.1
g = 9.81

s = np.array([0.0, 0.0])
v = np.array([10.0, 10.0])
dt = 0.01
time = 5

def resistance_force(v, q):
    return -q * v

def gravity_force(m):
    return np.array([0, -m * g])

def euler_method(s, v, a, dt):
    v_new = v + a * dt
    s_new = s + v_new * dt
    return s_new, v_new

def heun_method(s, v, a, dt):
    v_new = v + a * dt
    s_pred = s + v_new * dt
    a_pred = (gravity_force(m) + resistance_force(v_new, q)) / m
    v_corr = (v + v_new) / 2
    s_new = s + v_corr * dt
    return s_new, v_corr

trajektoria_euler = [s.copy()]
trajektoria_heun = [s.copy()]
for _ in np.arange(0, time, dt):

    F_resistance = resistance_force(v, q)
    F_gravity = gravity_force(m)
    F = F_resistance + F_gravity
    a = F / m

    s, v = euler_method(s, v, a, dt)
    trajektoria_euler.append(s.copy())

    s_heun, v_heun = heun_method(trajektoria_heun[-1], v, a, dt)
    trajektoria_heun.append(s_heun.copy())

trajektoria_euler = np.array(trajektoria_euler)
trajektoria_heun = np.array(trajektoria_heun)

plt.figure(figsize=(12, 6))
plt.plot(trajektoria_euler[:,0], trajektoria_euler[:,1], label='Metoda Eulera')
plt.plot(trajektoria_heun[:,0], trajektoria_heun[:,1], label='Ulepszona Metoda Eulera (Heun)', linestyle='--')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Trajektoria ruchu punktu materialnego')
plt.legend()
plt.show()